index:
    path: /api
    controller: App\Controller\URLShortenerController::index

admin_login:
    path: /login
    controller: App\Admin\Security\SecurityController::login

admin_logout:
    path: /logout
    controller: App\Admin\Security\SecurityController::logout

admin_index:
    path: /admin/
    controller: App\Admin\Dashboard\MyDashboard::index

authentication_token:
    path: /authentication_token
    methods: ['POST']

store-login-check-check:
    path: /api/store-login-check

set_url:
    path: /api/set_url
    controller: App\Controller\URLSetterController

lista_compra:
    path: /api/lista-compra/2021/noviembre/primera-semana/mercadona/{value}
    controller: App\Controller\TestUrlsController::index

short_url:
    path: /home/{value}
    controller: App\Controller\ShortUrlController

ranking_urls:
    path: /api/ranking
    controller: App\Controller\RankingController::index
